
DefaultContentLanguage = "ja"
languageCode = "ja-JP"

baseURL = "https://pepese.github.io/"
title = "ぺーぺーSEのテックブログ"
theme = "mainroad"
enableRobotsTXT = true
googleAnalytics = "UA-42388425-3"

[Params]
  description = "備忘録用メモサイト"
  twitter_cards = true
  readmore = true

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["social", "recent", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  twitter = "PeePeeSE"
  github = "pepese"

[taxonomies]
	tag = "tags"
	category = "categories"
	archive = "archives"